language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
deploy:
  provider: releases
  api_key:
    secure: Ag72xsfGKT91hGQL7+r1/dj47v2TnioV2zkjer8/hRw/NZAaNSKe6dRk52MPaOTiYTyYlstbeobz1iK8kq6UxHAsQDy51rgJXBIHMg1n62P0fYNjRqPANvtkYrLBJ5NYQTqD/oWjoLETEkqqSqEQjX1nlWzNOHHtdVZIcp4GZ1Gs8BWD/DispEQhpFHj3yF+3sISYyGGa5K9IhRqWUckSPBhGMQ/7GFi6s64BOjaSQJv9laPx2cUowZMgTL2idpkYYO57EJ039mve3JLp8BYWlnuK92mfajxfAyyHqCcqUmbVMd6+ZeH1FDLh2xriVO6YET3CmLPOK35TpHnxAIzbF5vv0U8GEkJF6TcqoBGKt/ziztWdbsMoHm7DOAMs40c/tSvUz0cXCyFk4in92+UsWJz6W3bNORszWr31/Ms6+SAjl1ORVQFC6hsC00Fndp3AiuuOF37ZcbeafDWnF4YuZsPTFlrFd2bIC14mc/YRudr/Rz6/S28h+JcSkaBhfeY9Mv8ZhlnkSS0eQKTW7htGkmWV584NlOutQR0QElLtlhcz8duHhAwUoU0SDWYJlBBD5aP0Icx3yzzufVOo0xeL9tDQWMhcAW20Jp8zOeF3Ru/UwU5nFoIibwIQb5uNz4UqHI5N/IpjsqCaMniDT2EQIrVCMSeFehkjR6TbmeW1Ek=
  file: target/validation-report.jar
  skip_cleanup: true
  on:
    repo: hl7-tools/validation-report
    tag: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[1-9][0-9]*[.](0|[1-9][0-9]*)[.](0|[1-9][0-9]*)$"
